### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by xVolar** [iZeaoGamer/Koth-v3.0#28]
If someone died he keep spawning in Koth setspawn place is there way to make him to go to hub or something ?

**Comment by iZeaoGamer** [comment]
Please try with the latest dev build. Though this doesn’t actually fix your current problem, but it fixes it for future use of this plugin. I may add an actual fix for current owners soon.

**Comment by xVolar** [comment]
Hey is it possible to make it that if player die they spawn at hub so player don’t keeps dying ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by iZeaoGamer** [comment]
The current koth system allows you to respawn in a random spawnpoint through out the koth world. I may make this optional though. But the koth plugin should allow you to respawn in the koth area, because otherwise, how would they be able to get back to the koth arena? The purpose of koth is to dedicate, and play king of the hill. When you die, you spawn back at the koth arena, but random locations to prevent spawn killing. I may add some sort of system in the future, where you have a few seconds without PvP (after being killed) to prevent spawn killing even more.

**Comment by xVolar** [comment]
I suggest that if someone do /Koth join he gets teleported to arena then if he died he go back to hub and if he want to join Koth again he should do /Koth join

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
